### ISSUE TITLE
Add template feature

### ISSUE THREAD

**Issue by vetom** [wistcc/werewolf-brain#5]
Template feature allows the user to create a game based on our templates. Several examples below.

#### Basic
- Werewolves
- Villagers

#### Novice
- Werewolves
- Villagers 
- Seer 
- Mayor

#### Amateur
- Werewolves
- Wolf cub 
- Villagers 
- Mayor 
- Seer 
- Witch 
- Prince
- Tanner

#### Wolfpack
- Werewolves
- Big Bad Wolf
- Wolf Cub
- Lone Wolf
- Fruit Brute
- Dream Wolf
- Villagers 
- Seer 
- Prince
- Mayor
- Martyr

#### Competent
- Werewolves
- Wolf cub 
- Sorcerer
- Cursed
- Minion
- Wild Child
- Villagers 
- Mayor 
- Seer 
- Witch 
- Prince
- Cult Leader
- Cupid
- Diseased
- Doppelgänger
- Lycan
- Spellcaster
- Tanner
- Mason
- Bodyguard
- Apprentice Seer
- Drunk

**Comment by mamodom** [comment]
I was talking with @wistcc and I think it'll be better if there is an "include/exclude" feature (That would allow the moderator to build a deck with a subset of the available roles). And build templates upon that

**Comment by vetom** [comment]
@mamodom thanks for the suggestion! In that case, you can build your own deck and call the getBalancedGame function passing that deck as a second parameter, also you can create your own cards and add it to that custom deck!
